M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date czw, 25 lip 2024, 18:58:18
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-25T18:58:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.1Y-1.3
X4.1Y-5.8
X7.5Y-1.3
X7.5Y-5.8
M30
